### ISSUE TITLE
Trouble with running PySC2

### ISSUE THREAD

**Issue by EmpereurCC** [inoryy/reaver#20] opened 2019-01-15 14:34 UTC
Hey I created an env on conda to test reaver and when i tried the command to try Beacon I had the logger issue. I followed your hotfix but I end up having weird errors depending on the agent I specify (A2C/PPO).
For PPO for instance I get this error : 

`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tf\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\tf\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\reaver\envs\base\msg_multiproc.py", line 48, in _run
    obs = self._env.reset()
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\reaver\envs\sc2.py", line 73, in reset
    obs, reward, done = self.obs_wrapper(self._env.reset())
  File "C:\ProgramData\Anaconda3\envs\tf\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\tf\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\reaver\envs\sc2.py", line 130, in __call__
    obs['feature_screen'][self.feature_masks['screen']],
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\pysc2\lib\named_array.py", line 145, in __getitem__
    index = _get_index(obj, index)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\pysc2\lib\named_array.py", line 207, in _get_index
    "Can't index by type: %s; only int, string or slice" % type(index))
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\reaver\envs\base\msg_multiproc.py", line 48, in _run
    obs = self._env.reset()
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\reaver\envs\base\msg_multiproc.py", line 48, in _run
    obs = self._env.reset()
TypeError: Can't index by type: <class 'list'>; only int, string or slice
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\reaver\envs\sc2.py", line 73, in reset
    obs, reward, done = self.obs_wrapper(self._env.reset())
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\reaver\envs\sc2.py", line 73, in reset
    obs, reward, done = self.obs_wrapper(self._env.reset())
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\reaver\envs\sc2.py", line 130, in __call__
    obs['feature_screen'][self.feature_masks['screen']],
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\reaver\envs\sc2.py", line 130, in __call__
    obs['feature_screen'][self.feature_masks['screen']],
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\pysc2\lib\named_array.py", line 145, in __getitem__
    index = _get_index(obj, index)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\pysc2\lib\named_array.py", line 145, in __getitem__
    index = _get_index(obj, index)
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\pysc2\lib\named_array.py", line 207, in _get_index
    "Can't index by type: %s; only int, string or slice" % type(index))
  File "C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\pysc2\lib\named_array.py", line 207, in _get_index
    "Can't index by type: %s; only int, string or slice" % type(index))
TypeError: Can't index by type: <class 'list'>; only int, string or slice
TypeError: Can't index by type: <class 'list'>; only int, string or slice`

I love your work anyway and looking forward a fix thanks

**Comment by inoryy** [comment] 2019-01-15 14:59
Hello, I don't think this issue is related to logger. Have you followed [Windows installation instructions](https://github.com/inoryy/reaver-pysc2/wiki/Windows)?

**Comment by EmpereurCC** [comment] 2019-01-15 15:06
Hello, thanks for the swift reply. I think I did follow the windows instructions but maybe something went wrong. 4 windows of SC2 open and nothing happends and I get this message.

**Comment by inoryy** [comment] 2019-01-15 15:09
Can you verify you've installed PySC2 from source? If yes, what command specifically do you use to run?

**Comment by EmpereurCC** [comment] 2019-01-15 16:11
I think I did install it from source : pip install https://github.com/deepmind/pysc2/archive/master.zip 

I make my run through this : 
import reaver as rvr

env = rvr.envs.SC2Env(map_name='MoveToBeacon')
agent = rvr.agents.A2C(env.obs_spec(), env.act_spec(), rvr.models.build_fully_conv, rvr.models.SC2MultiPolicy, n_envs=4)
agent.logger = rvr.utils.Logger()
agent.run(env)

**Comment by inoryy** [comment] 2019-01-15 16:52
Hmm, I still think the issue is due to PySC2 version mismatch. Could you install it once more with forced upgrade? E.g. run

```
pip install --upgrade https://github.com/deepmind/pysc2/archive/master.zip
```

---

btw I've added a default logger, run `pip install reaver` again to fetch the newer version

**Comment by inoryy** [comment] 2019-01-15 21:03
Issue was resolved by re-installing in a clean conda env

**Closed as completed by inoryy** 2019-01-15 21:03 UTC

**Comment by EmpereurCC** [comment] 2019-01-16 09:42
Problem solved! Thanks a lot!
